### ISSUE TITLE
`set-output` will be deprecated soon

### ISSUE THREAD

**Issue by itsankit-google** [ncipollo/release-action#266]
**Describe the bug**
Recently we started seeing these warnings on github actions - 
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Looks like the action is internally using `set-output` command which will be disabled soon by github.

**To Reproduce**
1. Run a workflow using ncipollo/release-action.

**Expected behavior**
Warning should not be seen.

**Additional context**
This action is really important for us and it is being used in an important workflow.

**Comment by ncipollo** [comment]
Hmm are you sure this is coming from the action and not elsewhere in your workflow? I'm not using the bash command, I'm using the GitHub typescript library to set output (and I would expect the to utilize the correct files internally)

**Comment by PetroSilenius** [comment]
The Github library seems to use `set-output` directly https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L192

I wonder if its usage could switched to `exportVariable` 🤔https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L83

**Comment by itsankit-google** [comment]
> The Github library seems to use `set-output` directly https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L192
> 
> I wonder if its usage could switched to `exportVariable` 🤔https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L83

But looks like they have recently environment file support to these commands - https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L193

**Comment by ncipollo** [comment]
I think setOutput is still the correct method to use, if you look closely at the implementation you will note that it writes to the new, correct location if GITHUB_OUTPUT exists in the environment. There real question here is why that variable doesn't seem to exist for some folks.

I'm away from my computer from a few days but I suspect this variable may not be present if you aren't correctly indicating that you want to use outputs from this step (or using them at all). If that's the case I'll add a check for that variable as well and avoid setting output if you don't have them setup.

**Comment by itsankit-google** [comment]
I think I know the issue, we are still using the older hash of your action and it recently got updated to use `actions/core v1.10.0` - https://github.com/ncipollo/release-action/pull/258.
ref - ``` Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.```

I think if you create a new release of your action, I can start using it and that should solve the issue.
Currently I am using - `ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37` i.e. `v1.10.0`

**Comment by ncipollo** [comment]
This release should have the latest core: https://github.com/ncipollo/release-action/releases/tag/v1.11.1

**Comment by itsankit-google** [comment]
Thanks, will try this out and update the issue.

**Comment by Crono1981** [comment]
Just ran with v1.11.1 (SHA 4c75f0f2e4ae5f3c807cf0904605408e319dcaac). Deprecation warning still shows, I'm afraid.

**Comment by ncipollo** [comment]
It looks like there is still a path where setOutput falls back on the deprecated file (if the output environment variable isn't provided). I'd look at your workflow and see if there is anything nonstandard in there. The action is using the documented mechanism of setting the output so I don't think there's anything to change here.

**Comment by Crono1981** [comment]
There's actually five jobs in my workflow. The last one is a dedicated release job which downloads two artifacts from a previous job and then at the very last step uses `ncipollo/release-action@v1`.

Unless my understanding of how GitHub Actions works is terribly wrong, by the time the deprecation warning is raised, the four previous job workers are already dead and buried.

So for the sake of conciseness (and for the sanity of whoever else is reading this because the original workflow is close to 500 lines of code and comments 😬), here's a trimmed down version. As you'll see, the steps of the first four jobs have been taken out but I've let their "skeleton" in place, for reference.

You obviously won't be able to take it as-is to reproduce the issue, but I'm hoping this may give you a few clues.

Thank you so much!

```yml
name: CI / CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_on_linux:
        description: Run on Linux (y/n)
        required: true
        default: 'y'
      run_on_macos:
        description: Run on MacOS (y/n)
        required: true
        default: 'n'
      run_on_windows:
        description: Run on Windows and create artifacts for NuGet packages and documentation (y/n)
        required: true
        default: 'n'
      create_release:
        description: Deliver to NuGet feed and create release (only available from main branch and if running on all OS) (y/n)
        required: true
        default: 'n'

defaults:
  run:
    shell: pwsh

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:

  data-gathering:    
    name: Gather data for pipeline
    runs-on: "ubuntu-22.04"
    outputs:
      version_semantic: ${{ steps.version.outputs.semantic }}
      version_assembly: ${{ steps.version.outputs.assembly }}
      version_assembly_file: ${{ steps.version.outputs.assembly_file }}
      version_informational: ${{ steps.version.outputs.informational }}
      repo_has_semver_commit_subject: ${{ steps.repo.outputs.has_semver_commit_subject }}

    # (steps were taken out on purpose)

  build-and-test-on-linux:
    name: Build and test libraries on Linux
    if: |
      (
          github.event_name == 'push'
          && fromJSON(needs.data-gathering.outputs.repo_has_semver_commit_subject)
      )
      || (
          github.event_name == 'workflow_dispatch'
          && github.event.inputs.run_on_linux == 'y'
      )
    needs:
      - data-gathering
    runs-on: "ubuntu-22.04"

    # (steps were taken out on purpose)

  build-and-test-on-macos:
    name: Build and test libraries on MacOS
    if: |
      (
        github.event_name == 'push'
        && fromJSON(needs.data-gathering.outputs.repo_has_semver_commit_subject)
      )
      || (
        github.event_name != 'workflow_dispatch'
        && github.event.inputs.run_on_macos == 'y'
      )
    needs:
      - data-gathering
    runs-on: "macos-12"

    # (steps were taken out on purpose)

  build-test-and-create-artifacts-on-windows:
    name: 'Build and test libraries on Windows, then create artifacts'
    if: |
      github.event_name != 'workflow_dispatch'
      || github.event.inputs.run_on_windows == 'y'
    needs:
      - data-gathering
    runs-on: "windows-2022"

    # (steps were taken out on purpose)

  create-release:
    # This runs only when the following conditions are met:

    # - Branch is "main"
    # - Workflow was triggered by either:
    #   - A git push command
    #   - A manual workflow dispatch with "create_release" input value of "y"
    # - Data gathering job succeeded
    # - Windows worker build job succeeded or was skipped*
    # - Linux worker build job succeeded or was skipped
    # - MacOS worker build job succeeded or was skipped

    # * If the Windows worker build job has been skipped then there won't be any artifacts to download and the release
    # job will fail.

    name: Create a release
    if: |
      always()
      && !cancelled()
      && github.ref == 'refs/heads/main'
      && needs.data-gathering.result == 'success'
      && contains(fromJson('["success", "skipped"]'), needs.build-and-test-on-linux.result)
      && contains(fromJson('["success", "skipped"]'), needs.build-and-test-on-macos.result)
      && contains(fromJson('["success", "skipped"]'), needs.build-test-and-create-artifacts-on-windows.result)
      && (
        github.event_name == 'push'
        || (
          github.event_name == 'workflow_dispatch'
          && github.event.inputs.create_release == 'y'
        )
      )
    needs:
      - data-gathering
      - build-and-test-on-linux
      - build-and-test-on-macos
      - build-test-and-create-artifacts-on-windows
    runs-on: "ubuntu-22.04"

    steps:
      - name: Download packages from artifact created in Windows build job
        uses: actions/download-artifact@v3
        with:
          name: packages-artifact
          path: ./packages

      - name: Download documentation files from artifact created in Windows build job
        uses: actions/download-artifact@v3
        with:
          name: doc-artifact
          path: ./doc

      - name: Compress documentation files to TAR archive
        working-directory: ./doc
        shell: bash
        run: |
          touch doc.tar.gz
          tar --xform s:'^./':: -czvf doc.tar.gz --exclude=doc.tar.gz .

      - name: Setup .NET 6.x (required for pushing to NuGet feed)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push packages to GitHub Packages
        run: |
          dotnet nuget push ./packages/*.*nupkg

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./doc/doc.tar.gz
          tag: ${{ needs.data-gathering.outputs.version_semantic }}
          name: Release v${{ needs.data-gathering.outputs.version_semantic }}
          draft: false
          prerelease: false
```

**Comment by Crono1981** [comment]
Oh man, I believe I got it all wrong.

The warning is actually raised twice within the release job. GitHub will just mention the job, not the actual step that's causing the warning, but the "twice" part should have clued me in that it might actually be the two `actions/download-artifact@v3` steps that are causing this.

As it turns out, it is very, very much likely to be the case:

https://github.com/actions/download-artifact/issues/185

I'm so sorry, I shouldn't have let myself dismiss that possibility just because that action belongs to one of GitHub's very own (?) `actions` repositories. 🤦‍♂️
